var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/create-order/route.js")
R.c("server/chunks/[root-of-the-server]__0wv2xwr._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_next-internal_server_app_api_create-order_route_actions_06i.jcm.js")
R.m(97407)
module.exports=R.m(97407).exports
