var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/wechat/bind/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i.ff7u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xc0q9g.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0rdadfb._.js")
R.c("server/chunks/ssr/_06.r63d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_wechat_bind_layout_tsx_0v5yc83._.js")
R.c("server/chunks/ssr/_next-internal_server_app_wechat_bind_page_actions_0c9dn-j.js")
R.m(58087)
module.exports=R.m(58087).exports
