var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/orders/[id]/mark-paid/route.js")
R.c("server/chunks/[root-of-the-server]__0ig-3vr._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_next-internal_server_app_api_admin_orders_[id]_mark-paid_route_actions_0nbfy8u.js")
R.m(31312)
module.exports=R.m(31312).exports
