var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/affiliates/withdraw/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__05fva7g._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/src_lib_0t02j2t._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/0zjb_server_app_api_admin_affiliates_withdraw_[id]_route_actions_03d7r8n.js")
R.m(79738)
module.exports=R.m(79738).exports
