var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/affiliates/[id]/review/route.js")
R.c("server/chunks/[root-of-the-server]__0btejfa._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/src_lib_0t02j2t._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_affiliates_[id]_review_route_actions_0mo5457.js")
R.m(81516)
module.exports=R.m(81516).exports
