var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/orders/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__041bmn2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_ndn9k.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0rdadfb._.js")
R.c("server/chunks/ssr/_06.r63d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_orders_layout_tsx_0j5nqit._.js")
R.c("server/chunks/ssr/_next-internal_server_app_orders_[id]_page_actions_09awnm7.js")
R.m(17904)
module.exports=R.m(17904).exports
