// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/ab-tests" | "/admin/affiliates" | "/admin/analytics" | "/admin/lawyers" | "/admin/login" | "/admin/orders" | "/admin/payment-events" | "/admin/payments" | "/admin/refunds" | "/admin/users" | "/admin/wechat-menu" | "/admin/withdrawals" | "/affiliate" | "/affiliate/dashboard" | "/affiliate/poster" | "/dashboard" | "/doc-type" | "/editorial-policy" | "/guide" | "/guide/child-custody" | "/guide/divorce" | "/guide/during-marriage" | "/guide/gift" | "/guide/inheritance" | "/guide/pre-marriage" | "/knowledge" | "/knowledge/[category]/[slug]" | "/login" | "/methodology" | "/orders" | "/orders/[id]" | "/payment" | "/pricing" | "/privacy" | "/questionnaire" | "/register" | "/result" | "/terms" | "/tutorial" | "/wechat/bind" | "/wechat/callback-error" | "/wechat/oauth" | "/wechat/pc-confirm" | "/wechat/success"
type AppRouteHandlerRoutes = "/api/ab/assign" | "/api/ab/event" | "/api/account/invoice" | "/api/admin/affiliates" | "/api/admin/affiliates/[id]/review" | "/api/admin/affiliates/withdraw" | "/api/admin/affiliates/withdraw/[id]" | "/api/admin/auth" | "/api/admin/lawyers" | "/api/admin/orders" | "/api/admin/orders/[id]/mark-paid" | "/api/admin/orders/[id]/refund" | "/api/admin/payments" | "/api/admin/stats" | "/api/admin/users" | "/api/admin/wechat-menu" | "/api/affiliate/apply" | "/api/affiliate/click" | "/api/affiliate/downline" | "/api/affiliate/me" | "/api/affiliate/stats" | "/api/affiliate/withdraw" | "/api/affiliate/withdrawals" | "/api/articles" | "/api/auth/login" | "/api/auth/register" | "/api/auth/send-otp" | "/api/auth/verify-otp" | "/api/book-lawyer" | "/api/create-order" | "/api/dev/set-openid" | "/api/dev/test-mint" | "/api/generate-document" | "/api/generate-will" | "/api/orders/[orderId]" | "/api/payment" | "/api/payment/callback" | "/api/payment/hupijiao-callback" | "/api/payment/status" | "/api/revise" | "/api/wechat/admin/menu" | "/api/wechat/mp-callback" | "/api/wechat/oauth-callback" | "/api/wechat/pc-login-status" | "/api/wechat/pc-login-ticket" | "/api/wechat/pc-login-verify" | "/api/wechat/prepare-oauth" | "/api/wechat/send-cs-msg" | "/articles/[...slug]" | "/llms-full.txt" | "/wechat/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/orders" | "/payment" | "/questionnaire" | "/result" | "/wechat/bind"
type RedirectRoutes = "/guide" | "/guide/child-custody" | "/guide/divorce" | "/guide/during-marriage" | "/guide/gift" | "/guide/inheritance" | "/guide/pre-marriage"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/ab-tests": {}
  "/admin/affiliates": {}
  "/admin/analytics": {}
  "/admin/lawyers": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/payment-events": {}
  "/admin/payments": {}
  "/admin/refunds": {}
  "/admin/users": {}
  "/admin/wechat-menu": {}
  "/admin/withdrawals": {}
  "/affiliate": {}
  "/affiliate/dashboard": {}
  "/affiliate/poster": {}
  "/api/ab/assign": {}
  "/api/ab/event": {}
  "/api/account/invoice": {}
  "/api/admin/affiliates": {}
  "/api/admin/affiliates/[id]/review": { "id": string; }
  "/api/admin/affiliates/withdraw": {}
  "/api/admin/affiliates/withdraw/[id]": { "id": string; }
  "/api/admin/auth": {}
  "/api/admin/lawyers": {}
  "/api/admin/orders": {}
  "/api/admin/orders/[id]/mark-paid": { "id": string; }
  "/api/admin/orders/[id]/refund": { "id": string; }
  "/api/admin/payments": {}
  "/api/admin/stats": {}
  "/api/admin/users": {}
  "/api/admin/wechat-menu": {}
  "/api/affiliate/apply": {}
  "/api/affiliate/click": {}
  "/api/affiliate/downline": {}
  "/api/affiliate/me": {}
  "/api/affiliate/stats": {}
  "/api/affiliate/withdraw": {}
  "/api/affiliate/withdrawals": {}
  "/api/articles": {}
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/auth/send-otp": {}
  "/api/auth/verify-otp": {}
  "/api/book-lawyer": {}
  "/api/create-order": {}
  "/api/dev/set-openid": {}
  "/api/dev/test-mint": {}
  "/api/generate-document": {}
  "/api/generate-will": {}
  "/api/orders/[orderId]": { "orderId": string; }
  "/api/payment": {}
  "/api/payment/callback": {}
  "/api/payment/hupijiao-callback": {}
  "/api/payment/status": {}
  "/api/revise": {}
  "/api/wechat/admin/menu": {}
  "/api/wechat/mp-callback": {}
  "/api/wechat/oauth-callback": {}
  "/api/wechat/pc-login-status": {}
  "/api/wechat/pc-login-ticket": {}
  "/api/wechat/pc-login-verify": {}
  "/api/wechat/prepare-oauth": {}
  "/api/wechat/send-cs-msg": {}
  "/articles/[...slug]": { "slug": string[]; }
  "/dashboard": {}
  "/doc-type": {}
  "/editorial-policy": {}
  "/guide": {}
  "/guide/child-custody": {}
  "/guide/divorce": {}
  "/guide/during-marriage": {}
  "/guide/gift": {}
  "/guide/inheritance": {}
  "/guide/pre-marriage": {}
  "/knowledge": {}
  "/knowledge/[category]/[slug]": { "category": string; "slug": string; }
  "/llms-full.txt": {}
  "/login": {}
  "/methodology": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/payment": {}
  "/pricing": {}
  "/privacy": {}
  "/questionnaire": {}
  "/register": {}
  "/result": {}
  "/terms": {}
  "/tutorial": {}
  "/wechat/bind": {}
  "/wechat/callback": {}
  "/wechat/callback-error": {}
  "/wechat/oauth": {}
  "/wechat/pc-confirm": {}
  "/wechat/success": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/orders": never
  "/payment": never
  "/questionnaire": never
  "/result": never
  "/wechat/bind": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
