// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/affiliate/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/affiliate/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/affiliate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/affiliate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/affiliate/poster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate/poster">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/affiliate/poster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/doc-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doc-type">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/doc-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/child-custody/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/child-custody">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/child-custody/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/divorce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/divorce">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/divorce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/during-marriage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/during-marriage">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/during-marriage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/gift/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/gift">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/gift/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/inheritance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/inheritance">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/inheritance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/guide/pre-marriage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/pre-marriage">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/guide/pre-marriage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/knowledge/[category]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/[category]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/knowledge/[category]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/methodology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/methodology">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/methodology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/result">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/tutorial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutorial">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/tutorial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/ab-tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ab-tests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/ab-tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/affiliates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliates">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/affiliates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/lawyers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lawyers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/lawyers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/payment-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payment-events">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/payment-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/wechat-menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/wechat-menu">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/wechat-menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/withdrawals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/withdrawals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/withdrawals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/editorial-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editorial-policy">> = Specific
  const handler = {} as typeof import("../../src/app/editorial-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/questionnaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questionnaire">> = Specific
  const handler = {} as typeof import("../../src/app/questionnaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/bind/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wechat/bind">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/bind/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/callback-error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wechat/callback-error">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/callback-error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/oauth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wechat/oauth">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/oauth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/pc-confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wechat/pc-confirm">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/pc-confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wechat/success">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ab/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ab/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/ab/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ab/event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ab/event">> = Specific
  const handler = {} as typeof import("../../src/app/api/ab/event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/affiliates/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/affiliates/[id]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/affiliates/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/affiliates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/affiliates">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/affiliates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/affiliates/withdraw/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/affiliates/withdraw/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/affiliates/withdraw/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/affiliates/withdraw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/affiliates/withdraw">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/affiliates/withdraw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lawyers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lawyers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lawyers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/[id]/mark-paid/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[id]/mark-paid">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/[id]/mark-paid/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/[id]/refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[id]/refund">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/[id]/refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/wechat-menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wechat-menu">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/wechat-menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/click/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/click">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/click/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/downline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/downline">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/downline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/withdraw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/withdraw">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/withdraw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affiliate/withdrawals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/withdrawals">> = Specific
  const handler = {} as typeof import("../../src/app/api/affiliate/withdrawals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/articles">> = Specific
  const handler = {} as typeof import("../../src/app/api/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/book-lawyer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/book-lawyer">> = Specific
  const handler = {} as typeof import("../../src/app/api/book-lawyer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/set-openid/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/set-openid">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/set-openid/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/test-mint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/test-mint">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/test-mint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-document">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-will/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-will">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-will/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/hupijiao-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/hupijiao-callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/hupijiao-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revise/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revise">> = Specific
  const handler = {} as typeof import("../../src/app/api/revise/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/admin/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/admin/menu">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/admin/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/mp-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/mp-callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/mp-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/oauth-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/oauth-callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/oauth-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/pc-login-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/pc-login-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/pc-login-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/pc-login-ticket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/pc-login-ticket">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/pc-login-ticket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/pc-login-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/pc-login-verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/pc-login-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/prepare-oauth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/prepare-oauth">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/prepare-oauth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/send-cs-msg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/send-cs-msg">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/send-cs-msg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/articles/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/articles/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/articles/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms-full.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms-full.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms-full.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/wechat/callback">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/payment/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/payment">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/payment/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/result/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/result">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/result/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(authed)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(authed)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/questionnaire/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/questionnaire">> = Specific
  const handler = {} as typeof import("../../src/app/questionnaire/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wechat/bind/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/wechat/bind">> = Specific
  const handler = {} as typeof import("../../src/app/wechat/bind/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
