var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/wechat/oauth-callback/route.js")
R.c("server/chunks/[root-of-the-server]__0~-lzpq._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_00aizrp.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/_next-internal_server_app_api_wechat_oauth-callback_route_actions_0ouak03.js")
R.m(38775)
module.exports=R.m(38775).exports
