var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/affiliate/withdrawals/route.js")
R.c("server/chunks/[root-of-the-server]__0kusuap._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/src_lib_0t02j2t._.js")
R.c("server/chunks/_10a_wi8._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/_next-internal_server_app_api_affiliate_withdrawals_route_actions_0xndjws.js")
R.m(73436)
module.exports=R.m(73436).exports
